vich_uploader:
    db_driver: orm
    mappings:
        moteur_images:
            uri_prefix: /images/moteurs
            upload_destination: '%kernel.project_dir%/public/images/moteurs'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
